title: Evan Timko
logo: IMG_0316.JPG
description: As a driven and inquisitive tech enthusiast, I constantly explore the ever-evolving world of technology. With a passion for learning, I embrace every opportunity to grow and push the boundaries of what’s possible.
show_downloads: true
theme: jekyll-theme-minimal
